import CollectionPage from '../_collection/CollectionPage';

const beachesData = {
    id: 'beaches',
    title: 'Sun & Sand',
    subtitle: 'Beach Destinations',
    headline: 'Sri Lanka\'s Finest Shores',
    description: 'From the vibrant coral reefs of Hikkaduwa to the whale-watching haven of Mirissa, Sri Lanka\'s coastline offers an extraordinary tapestry of golden beaches, turquoise lagoons, and world-class surf breaks. Each stretch of sand tells a unique story of the island\'s rich coastal culture.',
    heroImage: '/assets/sun-and-sand-top-banner.webp',
    accentColor: '#3B9ED4',
    accentGradient: 'linear-gradient(135deg, #0E4D8C 0%, #3B9ED4 100%)',
    stats: [
        { value: '1,340', label: 'km of Coastline' },
        { value: '7', label: 'Beach Destinations' },
        { value: '12', label: 'Surf Breaks' },
        { value: '365', label: 'Days of Sun' },
    ],
    destinations: [
        {
            id: 'hikkaduwa',
            name: 'Hikkaduwa',
            type: 'Snorkeling Haven',
            tagline: 'Vibrant Coral Reefs & Surf',
            image: '/assets/hikkaduwa-beach-1.webp',
            description: 'Famous for its vibrant, shallow coral sanctuaries, Hikkaduwa is the original backpacker beach of Sri Lanka. Sea turtles swim right up to the shore.',
            bestTime: 'Nov – Apr',
            famousFor: 'Coral Reefs & Turtles',
            highlights: ['Coral Sanctuary', 'Surfing', 'Sea Turtles'],
        },
        {
            id: 'unawatuna',
            name: 'Unawatuna',
            type: 'Golden Bay',
            tagline: 'The Picturesque Curve',
            image: '/assets/unawatuna-beach-1.webp',
            description: 'A banana-shaped beach lined with leaning palm trees. The water is exceptionally calm thanks to a protective reef, ideal for swimming.',
            bestTime: 'Nov – Apr',
            famousFor: 'Calm Swimming & Beach Bars',
            highlights: ['Japanese Peace Pagoda', 'Scuba Diving', 'Jungle Beach'],
        },
        {
            id: 'mirissa',
            name: 'Mirissa',
            type: 'Whale Watching Capital',
            tagline: 'Where Blue Whales Roam',
            image: '/assets/mirissa-1.webp',
            description: 'Renowned globally as one of the best locations to witness Blue Whales. A stunning crescent beach with a deeply relaxed tropical surfer vibe.',
            bestTime: 'Dec – Mar',
            famousFor: 'Blue Whales & Coconut Tree Hill',
            highlights: ['Whale Watching', 'Surfing', 'Coconut Tree Hill'],
        },
        {
            id: 'galle',
            name: 'Galle',
            type: 'Colonial Fort & Coast',
            tagline: 'A Living 400-Year-Old Fortress',
            image: '/assets/galle-1.webp',
            description: 'A UNESCO World Heritage fortress where European colonial architecture meets South Asian traditions. Boutique lanes, cafés, and ramparts overlooking the ocean.',
            bestTime: 'Dec – Mar',
            famousFor: 'Dutch Fort & Boutique Lanes',
            highlights: ['Fort Ramparts', 'Lighthouse', 'Dutch Heritage'],
        },
        {
            id: 'weligama',
            name: 'Weligama',
            type: 'Surf Town',
            tagline: 'Beginner\'s Surf Paradise',
            image: '/assets/weligama-beach.webp',
            description: 'A wide, sheltered bay perfect for learning to surf. Weligama offers consistent, gentle waves and is a mecca for beginner and intermediate surfers globally.',
            bestTime: 'Nov – Apr',
            famousFor: 'Surfing & Stilt Fishermen',
            highlights: ['Surf Schools', 'Stilt Fishing', 'Taprobane Island'],
        },
        {
            id: 'negombo',
            name: 'Negombo',
            type: 'Beach Town',
            tagline: 'Little Rome of the West Coast',
            image: '/assets/negombo-1.webp',
            description: 'Just north of Colombo, heavily influenced by colonial history. Known for its Catholic churches, Dutch canals, golden beaches, and giant fish markets.',
            bestTime: 'Dec – Apr',
            famousFor: 'Seafood, Canals & Beaches',
            highlights: ['Fish Market', 'Dutch Canal', 'Lagoon Boat Rides'],
        },
        {
            id: 'trincomalee',
            name: 'Trincomalee',
            type: 'Turquoise Lagoon',
            tagline: 'The Natural Harbour of the East',
            image: '/assets/trincomalee-1.webp',
            description: 'The east coast\'s crown jewel with some of the most pristine, uncrowded white sand beaches and one of the finest natural deep-water harbours in the world.',
            bestTime: 'May – Sep',
            famousFor: 'Whale Watching & Pigeon Island',
            highlights: ['Pigeon Island', 'Fort Frederick', 'Whale Watching'],
        },
    ],
    relatedTour: { label: 'Coastal Escape Package', href: '/tours/coastal-escape' },
};

export default function BeachesPage() {
    return <CollectionPage data={beachesData} />;
}
