import CollectionPage from '../_collection/CollectionPage';

const wildlifeData = {
    id: 'wildlife',
    title: 'Wild Sri Lanka',
    subtitle: 'National Parks & Reserves',
    headline: 'Where Giants Roam Free',
    description: 'Sri Lanka is a wildlife paradise—one of Asia\'s premier biodiversity hotspots. With the world\'s highest leopard density, the largest Asian elephant gathering on Earth, swimming elephants, and extraordinary birdlife, the island\'s national parks deliver jaw-dropping wilderness encounters.',
    heroImage: '/assets/wild-life-sri-lanka-top-banner.webp',
    accentColor: '#4CAF50',
    accentGradient: 'linear-gradient(135deg, #1B5E20 0%, #4CAF50 100%)',
    stats: [
        { value: '26', label: 'Protected Areas' },
        { value: '407', label: 'Bird Species' },
        { value: '127', label: 'Mammal Species' },
        { value: '5', label: 'Major Safaris' },
    ],
    destinations: [
        {
            id: 'yala',
            name: 'Yala National Park',
            type: 'National Park',
            tagline: 'The Realm of the Leopard',
            image: '/assets/wild-life/yala-national-park-sri-lanka-1.webp',
            description: 'Covering 979 sq km, Yala holds the world\'s highest density of leopards. Alongside apex predators, it hosts vast elephant herds, sloth bears, and endemic species.',
            bestTime: 'Feb – Jul',
            famousFor: 'Leopard Safaris & Wildlife',
            highlights: ['Leopard Spotting', 'Elephant Herds', 'Rock Temples'],
        },
        {
            id: 'udawalawe',
            name: 'Udawalawe',
            type: 'National Park',
            tagline: 'Elephant Paradise',
            image: '/assets/udawalawe-national-park.webp',
            description: 'With open savannah-like landscapes, Udawalawe guarantees incredible elephant sightings year-round alongside the world-famous Elephant Transit Home.',
            bestTime: 'Year Round',
            famousFor: 'Elephant Transit Home',
            highlights: ['Elephant Herds', 'Transit Home', 'Bird Watching'],
        },
        {
            id: 'minneriya',
            name: 'Minneriya',
            type: 'National Park',
            tagline: 'The Great Elephant Gathering',
            image: '/assets/minneriya-park.webp',
            description: 'Each dry season, hundreds of elephants gather around the ancient Minneriya Tank—the largest gathering of Asian elephants on the planet.',
            bestTime: 'Jul – Oct',
            famousFor: 'The Elephant Gathering',
            highlights: ['The Great Gathering', 'Ancient Reservoir', 'Rich Birdlife'],
        },
        {
            id: 'wilpattu',
            name: 'Wilpattu',
            type: 'National Park',
            tagline: 'The Land of Lakes',
            image: '/assets/wild-life/yala-national-park-sri-lanka-1.webp',
            description: 'Sri Lanka\'s largest park, uniquely dotted with natural sand-rimmed lake basins called \'Villus\'. It offers one of the island\'s most authentic, uncrowded safari experiences.',
            bestTime: 'Feb – Oct',
            famousFor: 'Leopards & Natural Lakes',
            highlights: ['Villu Lakes', 'Leopards & Bears', 'Historical Sites'],
        },
        {
            id: 'galoya',
            name: 'Gal Oya National Park',
            type: 'National Park',
            tagline: 'The Untouched Wilderness',
            image: '/assets/galoya-national-park.webp',
            description: 'The country\'s most secluded park, famous for Sri Lanka\'s only boat safari. Witness elephants swimming between jungle islands in the enormous Senanayake Samudraya reservoir.',
            bestTime: 'Mar – Dec',
            famousFor: 'Swimming Elephants & Boat Safari',
            highlights: ['Boat Safari', 'Swimming Elephants', 'Vedda Village'],
        },
        {
            id: 'bundala',
            name: 'Bundala National Park',
            type: 'Ramsar Wetland',
            tagline: 'The Flamingo Sanctuary',
            image: '/assets/bundala-national-park.webp',
            description: 'A UNESCO Biosphere Reserve and a critically important wetland sanctuary. Home to thousands of migratory flamingos and some of Sri Lanka\'s best coastal bird watching.',
            bestTime: 'Nov – Mar',
            famousFor: 'Flamingos & Migratory Birds',
            highlights: ['Flamingo Flocks', 'Saltwater Lagoons', 'Sea Turtle Nesting'],
        },
    ],
    relatedTour: { label: 'Wildlife Safari Package', href: '/tours/wildlife-safari' },
};

export default function WildlifePage() {
    return <CollectionPage data={wildlifeData} />;
}
